### ISSUE TITLE
Cannot read property 'on' of null

### ISSUE THREAD

**Issue by da2x** [datproject/dat-doctor#17]
Welcome to Dat Doctor!

    Software Info:
      darwin x64
      Node v11.0.0
      Dat Doctor v2.1.0
      dat v13.11.4

    Running Basic Tests (Checks your Dat installation and network setup)

    ✔ Your address is: 198.51.100.5:62456
    ✖ Error loading native modules
      Unable to load utp-native.
      This will make it harder to connect peer-to-peer.
    ✔ Resolved Dat Doctor Server
    ⠼ Connecting to Dat Doctor, 45.55.78.106:8887/usr/local/lib/node_modules/dat/node_modules/discovery-swarm/index.js:456
        server.on('error', onerror)
              ^

    TypeError: Cannot read property 'on' of null
        at Swarm.listen (/usr/local/lib/node_modules/dat/node_modules/discovery-swarm/index.js:456:12)
        at runPublicPeerTest (/usr/local/lib/node_modules/dat/node_modules/dat-doctor/lib/public-test.js:32:6)
        at publicPeerTask (/usr/local/lib/node_modules/dat/node_modules/dat-doctor/lib/tasks-default.js:92:5)
        at Task.task (/usr/local/lib/node_modules/dat/node_modules/dat-doctor/lib/tasks-default.js:47:9)
        at /usr/local/lib/node_modules/dat/node_modules/neat-tasks/index.js:135:28
        at Task.skip (/usr/local/lib/node_modules/dat/node_modules/dat-doctor/lib/tasks-default.js:50:35)
        at Task.run (/usr/local/lib/node_modules/dat/node_modules/neat-tasks/index.js:134:8)
        at runTask (/usr/local/lib/node_modules/dat/node_modules/neat-tasks/index.js:55:18)
        at taskDone (/usr/local/lib/node_modules/dat/node_modules/neat-tasks/index.js:66:9)
        at done (/usr/local/lib/node_modules/dat/node_modules/neat-tasks/index.js:149:14)

**Comment by whoisgina** [comment]
Same here! 
```
Welcome to Dat Doctor!

Software Info:
  darwin x64
  Node v11.2.0
  Dat Doctor v2.1.0
  dat v13.11.4

Running Basic Tests (Checks your Dat installation and network setup)

✔ Your address is: 24.21.76.118:48698
✖ Error loading native modules
  Unable to load utp-native.
  This will make it harder to connect peer-to-peer.
✔ Resolved Dat Doctor Server
⠼ Looking for Doctor on the Dat network.../usr/local/lib/node_modules/dat/node_modules/discovery-swarm/index.js:456
    server.on('error', onerror)
           ^

TypeError: Cannot read property 'on' of null
    at Swarm.listen (/usr/local/lib/node_modules/dat/node_modules/discovery-swarm/index.js:456:12)
    at runPublicPeerTest (/usr/local/lib/node_modules/dat/node_modules/dat-doctor/lib/public-test.js:32:6)
    at publicPeerTask (/usr/local/lib/node_modules/dat/node_modules/dat-doctor/lib/tasks-default.js:92:5)
    at Task.task (/usr/local/lib/node_modules/dat/node_modules/dat-doctor/lib/tasks-default.js:47:9)
    at /usr/local/lib/node_modules/dat/node_modules/neat-tasks/index.js:135:28
    at Task.skip (/usr/local/lib/node_modules/dat/node_modules/dat-doctor/lib/tasks-default.js:50:35)
    at Task.run (/usr/local/lib/node_modules/dat/node_modules/neat-tasks/index.js:134:8)
    at runTask (/usr/local/lib/node_modules/dat/node_modules/neat-tasks/index.js:55:18)
    at taskDone (/usr/local/lib/node_modules/dat/node_modules/neat-tasks/index.js:66:9)
    at done (/usr/local/lib/node_modules/dat/node_modules/neat-tasks/index.js:153:5)
```

**Comment by ozuchi** [comment]
Same for me on VPS when with or without firewall (`ufw`)

```
Welcome to Dat Doctor!

Software Info:
  linux x64
  Node v10.15.1
  Dat Doctor v2.1.1
  dat v13.11.5

Running Basic Tests (Checks your Dat installation and network setup)

✔ Your address is: 178.128.220.163:52091
✖ Error loading native modules
  Unable to load utp-native.
  This will make it harder to connect peer-to-peer.
✔ Resolved Dat Doctor Server
⠼ Connected to Dat Doctor!/root/.nvm/versions/node/v10.15.1/lib/node_modules/dat/node_modules/discovery-swarm/index.js:455
    server.on('error', onerror)
           ^

TypeError: Cannot read property 'on' of null
    at Swarm.listen (/root/.nvm/versions/node/v10.15.1/lib/node_modules/dat/node_modules/discovery-swarm/index.js:455:12)
    at runPublicPeerTest (/root/.nvm/versions/node/v10.15.1/lib/node_modules/dat/node_modules/dat-doctor/lib/public-test.js:33:6)
    at publicPeerTask (/root/.nvm/versions/node/v10.15.1/lib/node_modules/dat/node_modules/dat-doctor/lib/tasks-default.js:92:5)
    at Task.task (/root/.nvm/versions/node/v10.15.1/lib/node_modules/dat/node_modules/dat-doctor/lib/tasks-default.js:47:9)
    at /root/.nvm/versions/node/v10.15.1/lib/node_modules/dat/node_modules/neat-tasks/index.js:135:28
    at Task.skip (/root/.nvm/versions/node/v10.15.1/lib/node_modules/dat/node_modules/dat-doctor/lib/tasks-default.js:50:35)
    at Task.run (/root/.nvm/versions/node/v10.15.1/lib/node_modules/dat/node_modules/neat-tasks/index.js:134:8)
    at runTask (/root/.nvm/versions/node/v10.15.1/lib/node_modules/dat/node_modules/neat-tasks/index.js:55:18)
    at taskDone (/root/.nvm/versions/node/v10.15.1/lib/node_modules/dat/node_modules/neat-tasks/index.js:66:9)
    at done (/root/.nvm/versions/node/v10.15.1/lib/node_modules/dat/node_modules/neat-tasks/index.js:149:14)
```
